using System.Reflection;
using System.Text;
using System.Windows.Forms;
using INIUtility;

namespace ReportsPlus.Utils.Config
{

    [ConfigHeader("ReportsPlus", "Author: Guess1m", "Config Version: 2.0.4", "I recommend you do not edit this file manually, instead use the in-game menu to edit the settings.")]
    [Obfuscation(Exclude = true, ApplyToMembers = true)]
    public sealed class ReportsPlusSettings
    {
        // Register Settings
        [ConfigOption("Settings", "ClientAddress", "The network address for the websocket server (e.g., localhost, 127.0.0.1).")]
        public string ClientAddress { get; set; } = "localhost";

        [ConfigOption("Settings", "ClientPort", "Port to use for websocket server (must be 1-65535).")]
        public int ClientPort { get; set; } = 6969;

        [ConfigOption("Intervals", "ContinuousUpdateInterval", "Interval (ms) for sending continuous updates to server (e.g. PlayerLocation, PoliceVehiclesLocation).", Min = 1000, Max = 60000)]
        public int ContinuousUpdateInterval { get; set; } = 15000;

        [ConfigOption("AutoConnect", "AutoConnectEnabled", "Automatically attempt to reconnect when disconnected.")]
        public bool AutoConnectEnabled { get; set; } = true;

        [ConfigOption("AutoConnect", "AutoConnectInterval", "Interval (ms) between auto-reconnect attempts.", Min = 5000, Max = 300000)]
        public int AutoConnectInterval { get; set; } = 15000;

        // keybinding for menu
        [ConfigOption("Keybindings", "MenuKey", "Key to toggle menu (e.g. F11). Must be capitalized.")]
        public KeyBinding MenuKey { get; set; } = new KeyBinding(Keys.F11, Keys.Control);

        // keybinding for input-lock
        [ConfigOption("Keybindings", "InputLockKey", "Key to toggle input lock (e.g. F9). Must be capitalized.")]
        public KeyBinding InputLockKey { get; set; } = new KeyBinding(Keys.F9, Keys.Control);

        // keybinding for give parking citation
        [ConfigOption("Keybindings", "GiveCitationKey", "Key to give out a citation (e.g. F3). Must be capitalized. This isn't used when you are using PR.")]
        public KeyBinding GiveCitationKey { get; set; } = new KeyBinding(Keys.F3, Keys.None);

        // keybinding for discarding vehicle citation
        [ConfigOption("Keybindings", "DiscardCitationKey", "Key to discard a citation (e.g. Delete). Must be capitalized. Always used for parking citations. Not used for printed when you are using PR.")]
        public KeyBinding DiscardCitationKey { get; set; } = new KeyBinding(Keys.Delete, Keys.None);

        // Status Overlay settings
        [ConfigOption("StatusOverlay", "StatusOverlayEnabled", "Show the MDT status overlay on screen.")]
        public bool StatusOverlayEnabled { get; set; } = false;

        [ConfigOption("StatusOverlay", "StatusOverlayLabel", "The text label displayed before the connection status.")]
        public string StatusOverlayLabel { get; set; } = "MDT Status:";

        [ConfigOption("StatusOverlay", "StatusOverlayX", "Horizontal screen position of the overlay (0-100).", Min = 0, Max = 100)]
        public int StatusOverlayX { get; set; } = 3;

        [ConfigOption("StatusOverlay", "StatusOverlayY", "Vertical screen position of the overlay (0-100).", Min = 0, Max = 100)]
        public int StatusOverlayY { get; set; } = 3;

        [ConfigOption("StatusOverlay", "StatusOverlaySize", "Text size of the overlay (10-100).", Min = 10, Max = 100)]
        public int StatusOverlaySize { get; set; } = 35;

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.AppendLine("--- ReportsPlus Loaded Settings ---");
            foreach (var prop in GetType().GetProperties())
                if (prop.GetCustomAttributes(typeof(ConfigOptionAttribute), false).Length > 0)
                    sb.AppendLine($" {prop.Name}: '{prop.GetValue(this)}'");
            sb.AppendLine("-----------------------------------");
            return sb.ToString();
        }
    }
}